apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "der-monitoring.fullname" . }}-zookeeper
  labels:
    {{- include "der-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          ports:
            - containerPort: {{ .Values.zookeeper.port }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.zookeeper.port }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    {{- include "der-monitoring.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.zookeeper.port }}
      targetPort: {{ .Values.zookeeper.port }}
  selector:
    app.kubernetes.io/component: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "der-monitoring.fullname" . }}-kafka
  labels:
    {{- include "der-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: {{ .Values.kafka.internalPort }}
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:{{ .Values.zookeeper.port }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:{{ .Values.kafka.internalPort }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    {{- include "der-monitoring.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.kafka.internalPort }}
      targetPort: {{ .Values.kafka.internalPort }}
  selector:
    app.kubernetes.io/component: kafka
